### ISSUE TITLE
Allow namespaces for scaffold templates

### ISSUE THREAD

**Issue by codeconsole** [grails3-plugins/scaffolding#120]
I accidentally pushed this update.   

Please review:

if you have a controller namespace:
```groovy
@Scaffold(RestfulServiceController<Sample>)
class SampleController {
   static namespace = 'admin'
}
```

with no views defined, it will first check `/templates/scaffolding/$namespace/${shortViewName}.gsp` before falling back on `/templates/scaffolding/${shortViewName}.gsp`

# The following changes were applied 
https://github.com/grails/scaffolding/commit/0807fcd182922f00f3f6fbfb13ea8449aa64e1e4

https://github.com/grails/scaffolding/blob/0807fcd182922f00f3f6fbfb13ea8449aa64e1e4/src/main/groovy/grails/plugin/scaffolding/ScaffoldingViewResolver.groovy#L117-L121

https://github.com/grails/scaffolding/blob/0807fcd182922f00f3f6fbfb13ea8449aa64e1e4/src/main/groovy/grails/plugin/scaffolding/ScaffoldingViewResolver.groovy#L73-L93

**Comment by jamesfredley** [comment]
This looks good and adds the feature of having namespace specific scaffolding views, if you want, while falling back to the standard `/templates/scaffolding/${shortViewName}.gsp` if you have not created them or are not using a namespace.

**Comment by matrei** [comment]
Isn't there a risk for null-pointer exceptions if not using the nullsafe navigator in the last two `if` statements where `!res.exists()` is used here:

```groovy
private Resource resolveResource(Class controllerClass, shortViewName) {
    Resource res = null
    if (Environment.isDevelopmentMode()) {
        res = new FileSystemResource(new File(BuildSettings.BASE_DIR, "src/main/templates/scaffolding/${shortViewName}.gsp"))
    }

    if (!res?.exists()) {
        def url = IOUtils.findResourceRelativeToClass(controllerClass, "/META-INF/templates/scaffolding/${shortViewName}.gsp")
        res = url ? new UrlResource(url) : null
    }

    if (!res.exists() && templateOverridePluginDescriptor) {
        def url = IOUtils.findResourceRelativeToClass(templateOverridePluginDescriptor, "/META-INF/templates/scaffolding/${shortViewName}.gsp")
        res = url ? new UrlResource(url) : null
    }

    if (!res.exists()) {
        res = resourceLoader.getResource("classpath:META-INF/templates/scaffolding/${shortViewName}.gsp")
    }
    res
}
```

**Comment by codeconsole** [comment]
@matrei I see your point.  This was existing logic that I did not modify.

https://github.com/grails/scaffolding/blob/43ed348352cb3efad34e27ed0b31037a86173ccd/src/main/groovy/grails/plugin/scaffolding/ScaffoldingViewResolver.groovy#L85-L107

Introduced [by this commit](https://github.com/grails/scaffolding/commit/38cb35bfa7683ccc4ff6667315a9691bda494133) and this issue https://github.com/grails/scaffolding/issues/18

Looking at it, the logic looks kind of stupid. Why would you check if it doesn't exist multiple times when it exists?

**Comment by matrei** [comment]
> Why would you check if it doesn't exist multiple times when it exists?

In this method, `res` could both be `null` and just not exist in the location.
However, when using `ResourceLoader.getResource(String)` you will never get a `null` back.

Or, do you mean that the logic could be written to return early?

**Comment by codeconsole** [comment]
@matrei  if you are in development mode and res exists, the 2 additional checks are unnecessary or you could just return out early which is another pull request.... https://github.com/grails/scaffolding/pull/122
